// import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer/Footer'
import SigninState from '@/context/signin/SigninState'
import Nav from '@/components/navbar/Nav'
import UiState from '@/context/ui/UiState'
import PropertyState from '@/context/PropertyState'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <PropertyState>

        <UiState>

        <SigninState>


        <Nav/>
        <div className='spaceee' ></div>
        {/* <Navbar  /> */}
        {children}
        <Footer />
        </SigninState>
        </UiState>
        </PropertyState>
        </body>
    </html>
  )
}
